'use client';
import React, { useState } from 'react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { 
  Share2, Mail, MessageSquare, Download,
  FileText, CheckCircle, Clock, TrendingUp,
  Send, Users, Filter, Search
} from 'lucide-react';
import jsPDF from 'jspdf';

export const ShareToParents: React.FC = () => {
  const [selectedStudents, setSelectedStudents] = useState<string[]>([]);
  const [selectedTest, setSelectedTest] = useState<string | null>(null);
  const [shareMethod, setShareMethod] = useState<'email' | 'whatsapp' | 'download'>('email');
  const [isSending, setIsSending] = useState(false);

  // Mock data - replace with actual API calls
  const students = [
    { id: '1', name: 'Rahul Sharma', email: 'rahul.parent@email.com', phone: '+91 9876543210', batch: 'Batch A' },
    { id: '2', name: 'Priya Patel', email: 'priya.parent@email.com', phone: '+91 9876543211', batch: 'Batch B' },
    { id: '3', name: 'Amit Kumar', email: 'amit.parent@email.com', phone: '+91 9876543212', batch: 'Batch A' },
    { id: '4', name: 'Suresh Yadav', email: 'suresh.parent@email.com', phone: '+91 9876543213', batch: 'Batch C' },
    { id: '5', name: 'Neha Singh', email: 'neha.parent@email.com', phone: '+91 9876543214', batch: 'Batch B' },
  ];

  const tests = [
    { id: '1', title: 'Chapter 5 Test', subject: 'Mathematics', date: '2024-01-15', average: 72 },
    { id: '2', title: 'Physics Mid-Term', subject: 'Physics', date: '2024-01-20', average: 68 },
    { id: '3', title: 'Chemistry Quiz', subject: 'Chemistry', date: '2024-01-25', average: 75 },
  ];

  const performanceData = {
    studentName: 'Rahul Sharma',
    testName: 'Chapter 5 Test',
    subject: 'Mathematics',
    date: '2024-01-15',
    score: 85,
    totalMarks: 100,
    rank: 3,
    totalStudents: 45,
    averageScore: 72,
    strengths: ['Algebra', 'Geometry', 'Number Systems'],
    weaknesses: ['Calculus', 'Statistics'],
    recommendations: [
      'Focus on differentiation rules',
      'Practice integration problems',
      'Review statistical concepts'
    ],
    performanceTrend: 'improving',
    attendance: 92,
    behavior: 'Excellent'
  };

  const handleShare = async () => {
    setIsSending(true);
    // Simulate sharing - replace with actual API call
    setTimeout(() => {
      setIsSending(false);
      alert('Reports sent successfully!');
      setSelectedStudents([]);
    }, 2000);
  };

  const generatePDFReport = (student: any) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(24);
    doc.setTextColor(59, 130, 246);
    doc.text('Student Performance Report', 105, 20, { align: 'center' });
    
    // Student Info
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Student: ${student.name}`, 20, 40);
    doc.text(`Batch: ${student.batch}`, 20, 50);
    
    // Test Info
    doc.setFontSize(12);
    doc.setTextColor(80, 80, 80);
    doc.text(`Test: ${performanceData.testName}`, 20, 65);
    doc.text(`Subject: ${performanceData.subject}`, 20, 73);
    doc.text(`Date: ${performanceData.date}`, 20, 81);
    
    // Score Box
    doc.setFillColor(248, 250, 252);
    doc.rect(20, 90, 170, 40, 'F');
    doc.setFontSize(16);
    doc.setTextColor(59, 130, 246);
    doc.text(`Score: ${performanceData.score}/${performanceData.totalMarks}`, 30, 110);
    doc.setFontSize(12);
    doc.setTextColor(80, 80, 80);
    doc.text(`Rank: ${performanceData.rank} / ${performanceData.totalStudents}`, 30, 125);
    doc.text(`Class Average: ${performanceData.averageScore}%`, 30, 140);
    
    // Strengths
    doc.setFontSize(14);
    doc.setTextColor(34, 197, 94);
    doc.text('Strengths', 20, 160);
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    performanceData.strengths.forEach((strength, index) => {
      doc.text(`• ${strength}`, 25, 170 + (index * 8));
    });
    
    // Weaknesses
    doc.setFontSize(14);
    doc.setTextColor(239, 68, 68);
    doc.text('Areas for Improvement', 20, 200);
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    performanceData.weaknesses.forEach((weakness, index) => {
      doc.text(`• ${weakness}`, 25, 210 + (index * 8));
    });
    
    // Recommendations
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('Recommendations', 20, 240);
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    performanceData.recommendations.forEach((rec, index) => {
      doc.text(`${index + 1}. ${rec}`, 25, 250 + (index * 8));
    });
    
    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by EzzyCoach - Institute Management System', 105, 280, { align: 'center' });
    
    doc.save(`${student.name.replace(/\s+/g, '_')}_Performance_Report.pdf`);
  };

  const toggleStudentSelection = (studentId: string) => {
    setSelectedStudents(prev => 
      prev.includes(studentId) 
        ? prev.filter(id => id !== studentId)
        : [...prev, studentId]
    );
  };

  const selectAllStudents = () => {
    setSelectedStudents(students.map(s => s.id));
  };

  const clearSelection = () => {
    setSelectedStudents([]);
  };

  return (
    <div className="space-y-8 pb-20">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-brand-blue/10 flex items-center justify-center">
            <Share2 className="w-6 h-6 text-brand-blue" />
          </div>
          <div>
            <h2 className="text-2xl font-black text-text-slate tracking-tight">Share to Parents</h2>
            <p className="text-sm font-bold text-gray-400 mt-1">Share performance reports with parents</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="outline" className="h-10 px-4 rounded-xl font-black text-[10px] uppercase tracking-widest gap-2">
            <Filter className="w-4 h-4" /> Filter
          </Button>
          <Button className="h-10 px-4 rounded-xl bg-brand-blue font-black text-[10px] uppercase tracking-widest gap-2">
            <Download className="w-4 h-4" /> Bulk Export
          </Button>
        </div>
      </div>

      {/* Share Method Selection */}
      <Card className="p-6 border-none shadow-soft rounded-[24px] bg-white">
        <div className="flex items-center gap-4">
          <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Share Method:</p>
          <div className="flex items-center gap-2">
            {[
              { id: 'email', label: 'Email', icon: Mail },
              { id: 'whatsapp', label: 'WhatsApp', icon: MessageSquare },
              { id: 'download', label: 'Download PDF', icon: Download }
            ].map(method => {
              const Icon = method.icon;
              return (
                <button
                  key={method.id}
                  onClick={() => setShareMethod(method.id as any)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${
                    shareMethod === method.id
                      ? 'bg-brand-blue text-white shadow-lg shadow-brand-blue/20'
                      : 'bg-bg-soft/20 text-gray-400 hover:bg-bg-soft/30'
                  }`}
                >
                  <Icon className="w-4 h-4" />
                  {method.label}
                </button>
              );
            })}
          </div>
        </div>
      </Card>

      {/* Test Selection */}
      <Card className="p-6 border-none shadow-soft rounded-[24px] bg-white">
        <div className="flex items-center justify-between mb-4">
          <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Select Test:</p>
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input 
              placeholder="Search tests..."
              className="w-64 h-9 pl-10 pr-4 rounded-xl border border-gray-100 bg-bg-soft/10 text-xs font-bold focus:outline-none focus:ring-2 focus:ring-brand-blue/10"
            />
          </div>
        </div>
        <div className="flex items-center gap-3">
          {tests.map(test => (
            <button
              key={test.id}
              onClick={() => setSelectedTest(test.id)}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                selectedTest === test.id
                  ? 'bg-brand-blue text-white'
                  : 'bg-bg-soft/20 text-gray-400 hover:bg-bg-soft/30'
              }`}
            >
              {test.title}
            </button>
          ))}
        </div>
      </Card>

      {/* Student Selection */}
      <Card className="p-6 border-none shadow-soft rounded-[24px] bg-white">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-4">
            <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Select Students:</p>
            <Badge className="bg-brand-blue/10 text-brand-blue border-none font-black text-[9px] uppercase">
              {selectedStudents.length} selected
            </Badge>
          </div>
          <div className="flex items-center gap-2">
            <Button 
              variant="ghost" 
              size="sm"
              onClick={selectAllStudents}
              className="text-[10px] font-black uppercase tracking-widest"
            >
              Select All
            </Button>
            <Button 
              variant="ghost" 
              size="sm"
              onClick={clearSelection}
              className="text-[10px] font-black uppercase tracking-widest"
            >
              Clear
            </Button>
          </div>
        </div>
        
        <div className="grid grid-cols-3 gap-4">
          {students.map(student => (
            <div
              key={student.id}
              onClick={() => toggleStudentSelection(student.id)}
              className={`p-4 rounded-xl border-2 cursor-pointer transition-all ${
                selectedStudents.includes(student.id)
                  ? 'border-brand-blue bg-brand-blue/5'
                  : 'border-gray-100 bg-bg-soft/20 hover:border-gray-200'
              }`}
            >
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-brand-blue/10 flex items-center justify-center font-black text-brand-blue text-sm">
                    {student.name.charAt(0)}
                  </div>
                  <div>
                    <p className="font-black text-text-slate text-sm">{student.name}</p>
                    <p className="text-[10px] font-bold text-gray-400 uppercase">{student.batch}</p>
                  </div>
                </div>
                {selectedStudents.includes(student.id) && (
                  <CheckCircle className="w-5 h-5 text-brand-blue" />
                )}
              </div>
              <div className="flex items-center gap-2 text-[10px] font-bold text-gray-400">
                <Mail className="w-3 h-3" />
                {student.email}
              </div>
            </div>
          ))}
        </div>
      </Card>

      {/* Report Preview */}
      {selectedStudents.length > 0 && (
        <Card className="p-8 border-none shadow-soft rounded-[32px] bg-white">
          <div className="flex items-center gap-3 mb-6">
            <FileText className="w-5 h-5 text-brand-blue" />
            <h3 className="text-lg font-black text-text-slate">Report Preview</h3>
          </div>
          
          <div className="p-6 rounded-2xl bg-bg-soft/20 space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Student</p>
                <p className="font-black text-text-slate">{performanceData.studentName}</p>
              </div>
              <div className="text-right">
                <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Score</p>
                <p className="text-2xl font-black text-brand-blue">{performanceData.score}%</p>
              </div>
            </div>
            
            <div className="grid grid-cols-3 gap-4 pt-4 border-t border-gray-100">
              <div>
                <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Rank</p>
                <p className="font-black text-text-slate">{performanceData.rank} / {performanceData.totalStudents}</p>
              </div>
              <div>
                <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Class Average</p>
                <p className="font-black text-text-slate">{performanceData.averageScore}%</p>
              </div>
              <div>
                <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Trend</p>
                <Badge className="bg-green-100 text-green-600 border-none font-black text-[9px] uppercase">
                  {performanceData.performanceTrend}
                </Badge>
              </div>
            </div>

            <div className="pt-4 border-t border-gray-100">
              <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Strengths</p>
              <div className="flex flex-wrap gap-2">
                {performanceData.strengths.map((strength, index) => (
                  <Badge key={index} className="bg-green-50 text-green-600 border-none font-black text-[9px] uppercase">
                    {strength}
                  </Badge>
                ))}
              </div>
            </div>

            <div className="pt-4 border-t border-gray-100">
              <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Recommendations</p>
              <ul className="space-y-1">
                {performanceData.recommendations.map((rec, index) => (
                  <li key={index} className="text-xs font-bold text-gray-600 flex items-start gap-2">
                    <span className="text-brand-blue">•</span>
                    {rec}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </Card>
      )}

      {/* Send Button */}
      {selectedStudents.length > 0 && (
        <div className="flex items-center justify-end gap-4">
          <Button 
            variant="outline"
            onClick={() => selectedStudents.forEach(id => {
              const student = students.find(s => s.id === id);
              if (student) generatePDFReport(student);
            })}
            className="h-12 px-8 rounded-xl font-black text-[10px] uppercase tracking-widest gap-2"
          >
            <Download className="w-4 h-4" /> Download All Reports
          </Button>
          <Button 
            onClick={handleShare}
            disabled={isSending}
            className="h-12 px-8 rounded-xl bg-brand-blue font-black text-[10px] uppercase tracking-widest gap-2"
          >
            {isSending ? (
              <>
                <Clock className="w-4 h-4 animate-spin" /> Sending...
              </>
            ) : (
              <>
                <Send className="w-4 h-4" /> Send to {selectedStudents.length} Parents
              </>
            )}
          </Button>
        </div>
      )}
    </div>
  );
};
