export type LeadStage =
  | "New Lead"
  | "Contacted"
  | "Demo Scheduled"
  | "Demo Done"
  | "Proposal Sent"
  | "Negotiation"
  | "Converted"
  | "Lost";

export type ActivityType =
  | "call"
  | "email"
  | "whatsapp"
  | "demo"
  | "meeting"
  | "note"
  | "stage_change"
  | "proposal"
  | "follow_up";

export type FollowUpType = "Call" | "Email" | "WhatsApp" | "Demo" | "Meeting";
export type FollowUpStatus = "Pending" | "Done" | "Snoozed" | "Overdue";
export type DemoStatus = "Scheduled" | "Completed" | "Cancelled" | "No Show" | "Rescheduled";
export type DemoOutcome = "Very Interested" | "Interested" | "Neutral" | "Not Interested";

export interface Lead {
  id: string;
  instituteName: string;
  contactPerson: string;
  contactAvatar: string;
  phone: string;
  email: string;
  city: string;
  state: string;
  interestedPlan: "Free" | "Basic" | "Pro";
  stage: LeadStage;
  source: string;
  referredBy: string | null;
  assignedTo: string;
  expectedMRR: number;
  expectedCloseDate: string | null;
  daysInCurrentStage: number;
  totalDaysInPipeline: number;
  priority: "High" | "Medium" | "Low";
  tags: string[];
  notes: string;
  lastContactDate: string | null;
  nextFollowupDate: string | null;
  nextFollowupType: FollowUpType | null;
  demoDate: string | null;
  demoTime: string | null;
  demoMode: "Online" | "In-Person" | null;
  proposalSentDate: string | null;
  convertedDate: string | null;
  lostDate: string | null;
  lostReason: string | null;
  estimatedStudents: number;
  createdAt: string;
  updatedAt: string;
}

export interface LeadActivity {
  id: string;
  leadId: string;
  type: ActivityType;
  title: string;
  description: string;
  outcome: "Positive" | "Neutral" | "Negative" | null;
  performedBy: string;
  scheduledAt: string | null;
  completedAt: string | null;
  duration: number | null;
  nextAction: string | null;
  nextActionDate: string | null;
}

export interface FollowUp {
  id: string;
  leadId: string;
  leadName: string;
  contactPerson: string;
  phone: string;
  assignedTo: string;
  type: FollowUpType;
  scheduledDate: string;
  scheduledTime: string | null;
  notes: string;
  status: FollowUpStatus;
  priority: "High" | "Medium" | "Low";
  outcome: string | null;
  completedAt: string | null;
  snoozedUntil: string | null;
}

export interface Demo {
  id: string;
  leadId: string;
  leadName: string;
  contactPerson: string;
  phone: string;
  email: string;
  assignedTo: string;
  scheduledDate: string;
  scheduledTime: string;
  duration: number;
  mode: "Online" | "In-Person";
  meetLink: string | null;
  location: string | null;
  status: DemoStatus;
  outcome: DemoOutcome | null;
  notes: string;
  recordingLink: string | null;
  followUpScheduled: boolean;
}

export const leads: Lead[] = [
  {
    id: "LEAD001",
    instituteName: "Star Coaching Centre",
    contactPerson: "Ramesh Patil",
    contactAvatar: "RP",
    phone: "9871230001",
    email: "star@coaching.in",
    city: "Kolhapur",
    state: "MH",
    interestedPlan: "Pro",
    stage: "Negotiation",
    source: "Social Media",
    referredBy: "Ravi Tiwari",
    assignedTo: "Ravi Tiwari",
    expectedMRR: 1000,
    expectedCloseDate: "2026-04-23",
    daysInCurrentStage: 3,
    totalDaysInPipeline: 12,
    priority: "High",
    tags: ["Hot Lead"],
    notes: "Negotiating pricing — they want 20% off Pro plan",
    lastContactDate: "2026-04-10",
    nextFollowupDate: "2026-04-11",
    nextFollowupType: "Call",
    demoDate: "2026-04-05",
    demoTime: "11:00 AM",
    demoMode: "Online",
    proposalSentDate: "2026-04-08",
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 150,
    createdAt: "2026-04-01",
    updatedAt: "2026-04-10",
  },
  {
    id: "LEAD002",
    instituteName: "Gurukripa Classes",
    contactPerson: "Sunita Jain",
    contactAvatar: "SJ",
    phone: "9871230002",
    email: "guru@kripa.in",
    city: "Nagpur",
    state: "MH",
    interestedPlan: "Basic",
    stage: "Demo Done",
    source: "Website",
    referredBy: null,
    assignedTo: "Pooja Mehta",
    expectedMRR: 500,
    expectedCloseDate: "2026-04-30",
    daysInCurrentStage: 5,
    totalDaysInPipeline: 15,
    priority: "High",
    tags: [],
    notes: "Reviewing demo recording",
    lastContactDate: "2026-04-07",
    nextFollowupDate: "2026-04-11",
    nextFollowupType: "WhatsApp",
    demoDate: "2026-04-07",
    demoTime: "11:00 AM",
    demoMode: "In-Person",
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 80,
    createdAt: "2026-03-28",
    updatedAt: "2026-04-07",
  },
  {
    id: "LEAD003",
    instituteName: "NextStep Academy",
    contactPerson: "Anil Mehta",
    contactAvatar: "AM",
    phone: "9871230003",
    email: "nextstep@acad.in",
    city: "Pune",
    state: "MH",
    interestedPlan: "Pro",
    stage: "Demo Scheduled",
    source: "Google Ad",
    referredBy: null,
    assignedTo: "Ravi Tiwari",
    expectedMRR: 1000,
    expectedCloseDate: "2026-05-05",
    daysInCurrentStage: 8,
    totalDaysInPipeline: 20,
    priority: "High",
    tags: ["Hot Lead", "Large Institute"],
    notes: "Demo scheduled for 14 Apr",
    lastContactDate: "2026-04-04",
    nextFollowupDate: "2026-04-14",
    nextFollowupType: "Demo",
    demoDate: "2026-04-14",
    demoTime: "11:00 AM",
    demoMode: "Online",
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 200,
    createdAt: "2026-03-23",
    updatedAt: "2026-04-04",
  },
  {
    id: "LEAD004",
    instituteName: "Bright Minds Institute",
    contactPerson: "Kavita Sharma",
    contactAvatar: "KS",
    phone: "9871230004",
    email: "bright@minds.in",
    city: "Mumbai",
    state: "MH",
    interestedPlan: "Basic",
    stage: "Contacted",
    source: "Referral",
    referredBy: "Neha Gupta",
    assignedTo: "Neha Gupta",
    expectedMRR: 500,
    expectedCloseDate: "2026-05-15",
    daysInCurrentStage: 2,
    totalDaysInPipeline: 5,
    priority: "Medium",
    tags: [],
    notes: "Send product brochure",
    lastContactDate: "2026-04-09",
    nextFollowupDate: "2026-04-13",
    nextFollowupType: "Email",
    demoDate: null,
    demoTime: null,
    demoMode: null,
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 50,
    createdAt: "2026-04-07",
    updatedAt: "2026-04-09",
  },
  {
    id: "LEAD005",
    instituteName: "Achieve More Classes",
    contactPerson: "Deepak Rao",
    contactAvatar: "DR",
    phone: "9871230005",
    email: "achieve@more.in",
    city: "Nashik",
    state: "MH",
    interestedPlan: "Pro",
    stage: "New Lead",
    source: "WhatsApp",
    referredBy: null,
    assignedTo: "Ravi Tiwari",
    expectedMRR: 1000,
    expectedCloseDate: null,
    daysInCurrentStage: 1,
    totalDaysInPipeline: 1,
    priority: "Medium",
    tags: [],
    notes: "Newly added from WhatsApp inquiry",
    lastContactDate: null,
    nextFollowupDate: null,
    nextFollowupType: null,
    demoDate: null,
    demoTime: null,
    demoMode: null,
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 100,
    createdAt: "2026-04-11",
    updatedAt: "2026-04-11",
  },
  {
    id: "LEAD006",
    instituteName: "Prime Study Circle",
    contactPerson: "Priya Joshi",
    contactAvatar: "PJ",
    phone: "9871230006",
    email: "prime@study.in",
    city: "Solapur",
    state: "MH",
    interestedPlan: "Basic",
    stage: "New Lead",
    source: "Cold Call",
    referredBy: null,
    assignedTo: "Pooja Mehta",
    expectedMRR: 500,
    expectedCloseDate: null,
    daysInCurrentStage: 3,
    totalDaysInPipeline: 3,
    priority: "Low",
    tags: [],
    notes: "Initial cold call, call back later",
    lastContactDate: "2026-04-09",
    nextFollowupDate: "2026-04-10",
    nextFollowupType: "Call",
    demoDate: null,
    demoTime: null,
    demoMode: null,
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 40,
    createdAt: "2026-04-09",
    updatedAt: "2026-04-09",
  },
  {
    id: "LEAD007",
    instituteName: "Excel Coaching Hub",
    contactPerson: "Suresh Nair",
    contactAvatar: "SN",
    phone: "9871230007",
    email: "excel@coaching.in",
    city: "Aurangabad",
    state: "MH",
    interestedPlan: "Pro",
    stage: "Proposal Sent",
    source: "Exhibition",
    referredBy: null,
    assignedTo: "Ravi Tiwari",
    expectedMRR: 1000,
    expectedCloseDate: "2026-04-20",
    daysInCurrentStage: 4,
    totalDaysInPipeline: 15,
    priority: "High",
    tags: ["Hot Lead"],
    notes: "Proposal sent on 8 Apr, follow up now",
    lastContactDate: "2026-04-08",
    nextFollowupDate: "2026-04-11",
    nextFollowupType: "Call",
    demoDate: "2026-04-04",
    demoTime: "10:00 AM",
    demoMode: "In-Person",
    proposalSentDate: "2026-04-08",
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 250,
    createdAt: "2026-03-28",
    updatedAt: "2026-04-08",
  },
  {
    id: "LEAD008",
    instituteName: "Knowledge Tree",
    contactPerson: "Meera Desai",
    contactAvatar: "MD",
    phone: "9871230008",
    email: "knowledge@tree.in",
    city: "Pune",
    state: "MH",
    interestedPlan: "Basic",
    stage: "Contacted",
    source: "Google Ad",
    referredBy: null,
    assignedTo: "Neha Gupta",
    expectedMRR: 500,
    expectedCloseDate: "2026-05-10",
    daysInCurrentStage: 5,
    totalDaysInPipeline: 8,
    priority: "Medium",
    tags: [],
    notes: "Initial discussion done",
    lastContactDate: "2026-04-07",
    nextFollowupDate: "2026-04-13",
    nextFollowupType: "Call",
    demoDate: null,
    demoTime: null,
    demoMode: null,
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 75,
    createdAt: "2026-04-04",
    updatedAt: "2026-04-07",
  },
  {
    id: "LEAD009",
    instituteName: "Aspire Institute",
    contactPerson: "Rohit Gupta",
    contactAvatar: "RG",
    phone: "9871230009",
    email: "aspire@inst.in",
    city: "Hyderabad",
    state: "TS",
    interestedPlan: "Pro",
    stage: "Demo Done",
    source: "Referral",
    referredBy: "Ravi Tiwari",
    assignedTo: "Ravi Tiwari",
    expectedMRR: 1000,
    expectedCloseDate: "2026-04-25",
    daysInCurrentStage: 2,
    totalDaysInPipeline: 10,
    priority: "High",
    tags: ["Large Institute"],
    notes: "Demo done on 9 Apr",
    lastContactDate: "2026-04-09",
    nextFollowupDate: "2026-04-12",
    nextFollowupType: "Call",
    demoDate: "2026-04-09",
    demoTime: "2:00 PM",
    demoMode: "Online",
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 300,
    createdAt: "2026-04-02",
    updatedAt: "2026-04-09",
  },
  {
    id: "LEAD010",
    instituteName: "Zenith Classes",
    contactPerson: "Anita Kapoor",
    contactAvatar: "AK",
    phone: "9871230010",
    email: "zenith@classes.in",
    city: "Mumbai",
    state: "MH",
    interestedPlan: "Basic",
    stage: "New Lead",
    source: "Website",
    referredBy: null,
    assignedTo: "Pooja Mehta",
    expectedMRR: 500,
    expectedCloseDate: null,
    daysInCurrentStage: 5,
    totalDaysInPipeline: 5,
    priority: "Low",
    tags: [],
    notes: "Outreach email sent on 9 Apr",
    lastContactDate: "2026-04-09",
    nextFollowupDate: "2026-04-09",
    nextFollowupType: "Email",
    demoDate: null,
    demoTime: null,
    demoMode: null,
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 60,
    createdAt: "2026-04-07",
    updatedAt: "2026-04-09",
  },
  {
    id: "LEAD011",
    instituteName: "Spark Tutorials",
    contactPerson: "Vijay Patil",
    contactAvatar: "VP",
    phone: "9871230011",
    email: "spark@tut.in",
    city: "Nagpur",
    state: "MH",
    interestedPlan: "Pro",
    stage: "Negotiation",
    source: "Cold Call",
    referredBy: null,
    assignedTo: "Ravi Tiwari",
    expectedMRR: 1000,
    expectedCloseDate: "2026-04-18",
    daysInCurrentStage: 2,
    totalDaysInPipeline: 18,
    priority: "High",
    tags: ["Hot Lead"],
    notes: "Meeting on 12 Apr to close",
    lastContactDate: "2026-04-10",
    nextFollowupDate: "2026-04-12",
    nextFollowupType: "Meeting",
    demoDate: "2026-04-03",
    demoTime: "3:00 PM",
    demoMode: "In-Person",
    proposalSentDate: "2026-04-05",
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 120,
    createdAt: "2026-03-25",
    updatedAt: "2026-04-10",
  },
  {
    id: "LEAD012",
    instituteName: "Summit Coaching",
    contactPerson: "Nisha Rao",
    contactAvatar: "NR",
    phone: "9871230012",
    email: "summit@coach.in",
    city: "Pune",
    state: "MH",
    interestedPlan: "Basic",
    stage: "Converted",
    source: "Referral",
    referredBy: "Neha Gupta",
    assignedTo: "Neha Gupta",
    expectedMRR: 500,
    expectedCloseDate: null,
    daysInCurrentStage: 7,
    totalDaysInPipeline: 15,
    priority: "Medium",
    tags: [],
    notes: "Converted on 5 Apr",
    lastContactDate: "2026-04-05",
    nextFollowupDate: null,
    nextFollowupType: null,
    demoDate: "2026-04-01",
    demoTime: "11:00 AM",
    demoMode: "Online",
    proposalSentDate: "2026-04-03",
    convertedDate: "2026-04-05",
    lostDate: null,
    lostReason: null,
    estimatedStudents: 150,
    createdAt: "2026-03-21",
    updatedAt: "2026-04-05",
  },
  {
    id: "LEAD013",
    instituteName: "Horizon Institute",
    contactPerson: "Raj Kumar",
    contactAvatar: "RK",
    phone: "9871230013",
    email: "horizon@inst.in",
    city: "Kolhapur",
    state: "MH",
    interestedPlan: "Pro",
    stage: "Converted",
    source: "Google Ad",
    referredBy: null,
    assignedTo: "Ravi Tiwari",
    expectedMRR: 1000,
    expectedCloseDate: null,
    daysInCurrentStage: 11,
    totalDaysInPipeline: 18,
    priority: "High",
    tags: [],
    notes: "Converted on 1 Apr",
    lastContactDate: "2026-04-01",
    nextFollowupDate: null,
    nextFollowupType: null,
    demoDate: "2026-03-25",
    demoTime: "2:00 PM",
    demoMode: "Online",
    proposalSentDate: "2026-03-28",
    convertedDate: "2026-04-01",
    lostDate: null,
    lostReason: null,
    estimatedStudents: 220,
    createdAt: "2026-03-14",
    updatedAt: "2026-04-01",
  },
  {
    id: "LEAD014",
    instituteName: "Pinnacle Study Group",
    contactPerson: "Lata Sharma",
    contactAvatar: "LS",
    phone: "9871230014",
    email: "pinnacle@study.in",
    city: "Nashik",
    state: "MH",
    interestedPlan: "Basic",
    stage: "Lost",
    source: "Website",
    referredBy: null,
    assignedTo: "Pooja Mehta",
    expectedMRR: 500,
    expectedCloseDate: null,
    daysInCurrentStage: 4,
    totalDaysInPipeline: 12,
    priority: "Medium",
    tags: [],
    notes: "Lost on 8 Apr — Went to competitor",
    lastContactDate: "2026-04-08",
    nextFollowupDate: null,
    nextFollowupType: null,
    demoDate: "2026-04-04",
    demoTime: "4:00 PM",
    demoMode: "Online",
    proposalSentDate: null,
    convertedDate: null,
    lostDate: "2026-04-08",
    lostReason: "Went to competitor",
    estimatedStudents: 90,
    createdAt: "2026-03-27",
    updatedAt: "2026-04-08",
  },
  {
    id: "LEAD015",
    instituteName: "Milestone Coaching",
    contactPerson: "Arun Singh",
    contactAvatar: "AS",
    phone: "9871230015",
    email: "milestone@coach.in",
    city: "Pune",
    state: "MH",
    interestedPlan: "Pro",
    stage: "Lost",
    source: "Cold Call",
    referredBy: null,
    assignedTo: "Ravi Tiwari",
    expectedMRR: 1000,
    expectedCloseDate: null,
    daysInCurrentStage: 9,
    totalDaysInPipeline: 20,
    priority: "High",
    tags: [],
    notes: "Lost on 3 Apr — Price concern",
    lastContactDate: "2026-04-03",
    nextFollowupDate: null,
    nextFollowupType: null,
    demoDate: "2026-03-28",
    demoTime: "10:00 AM",
    demoMode: "In-Person",
    proposalSentDate: null,
    convertedDate: null,
    lostDate: "2026-04-03",
    lostReason: "Price concern",
    estimatedStudents: 150,
    createdAt: "2026-03-14",
    updatedAt: "2026-04-03",
  },
  {
    id: "LEAD016",
    instituteName: "Dream Academy",
    contactPerson: "Pooja Mehta",
    contactAvatar: "PM",
    phone: "9871230016",
    email: "dream@acad.in",
    city: "Mumbai",
    state: "MH",
    interestedPlan: "Pro",
    stage: "Demo Scheduled",
    source: "Social Media",
    referredBy: null,
    assignedTo: "Ravi Tiwari",
    expectedMRR: 1000,
    expectedCloseDate: "2026-05-08",
    daysInCurrentStage: 5,
    totalDaysInPipeline: 10,
    priority: "Medium",
    tags: [],
    notes: "Demo on 15 Apr",
    lastContactDate: "2026-04-07",
    nextFollowupDate: "2026-04-15",
    nextFollowupType: "Demo",
    demoDate: "2026-04-15",
    demoTime: "3:00 PM",
    demoMode: "Online",
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 120,
    createdAt: "2026-04-02",
    updatedAt: "2026-04-07",
  },
  {
    id: "LEAD017",
    instituteName: "Victory Classes",
    contactPerson: "Sunil Joshi",
    contactAvatar: "SJ",
    phone: "9871230017",
    email: "victory@classes.in",
    city: "Aurangabad",
    state: "MH",
    interestedPlan: "Basic",
    stage: "Contacted",
    source: "WhatsApp",
    referredBy: "Neha Gupta",
    assignedTo: "Neha Gupta",
    expectedMRR: 500,
    expectedCloseDate: "2026-05-20",
    daysInCurrentStage: 4,
    totalDaysInPipeline: 6,
    priority: "Low",
    tags: [],
    notes: "Sent intro message",
    lastContactDate: "2026-04-08",
    nextFollowupDate: "2026-04-08",
    nextFollowupType: "WhatsApp",
    demoDate: null,
    demoTime: null,
    demoMode: null,
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 40,
    createdAt: "2026-04-06",
    updatedAt: "2026-04-08",
  },
  {
    id: "LEAD018",
    instituteName: "Talent Grove",
    contactPerson: "Asha Patil",
    contactAvatar: "AP",
    phone: "9871230018",
    email: "talent@grove.in",
    city: "Pune",
    state: "MH",
    interestedPlan: "Pro",
    stage: "New Lead",
    source: "Exhibition",
    referredBy: null,
    assignedTo: "Pooja Mehta",
    expectedMRR: 1000,
    expectedCloseDate: null,
    daysInCurrentStage: 2,
    totalDaysInPipeline: 2,
    priority: "Medium",
    tags: [],
    notes: "Added from exhibition lead sheet",
    lastContactDate: null,
    nextFollowupDate: null,
    nextFollowupType: null,
    demoDate: null,
    demoTime: null,
    demoMode: null,
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 180,
    createdAt: "2026-04-10",
    updatedAt: "2026-04-10",
  },
  {
    id: "LEAD019",
    instituteName: "Focus Point Classes",
    contactPerson: "Ravi Sharma",
    contactAvatar: "RS",
    phone: "9871230019",
    email: "focus@point.in",
    city: "Mumbai",
    state: "MH",
    interestedPlan: "Basic",
    stage: "Contacted",
    source: "Google Ad",
    referredBy: null,
    assignedTo: "Neha Gupta",
    expectedMRR: 500,
    expectedCloseDate: "2026-05-05",
    daysInCurrentStage: 3,
    totalDaysInPipeline: 7,
    priority: "Medium",
    tags: [],
    notes: "Interested but needs trial",
    lastContactDate: "2026-04-09",
    nextFollowupDate: "2026-04-14",
    nextFollowupType: "WhatsApp",
    demoDate: null,
    demoTime: null,
    demoMode: null,
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 85,
    createdAt: "2026-04-05",
    updatedAt: "2026-04-09",
  },
  {
    id: "LEAD020",
    instituteName: "Champion Academy",
    contactPerson: "Dev Kapoor",
    contactAvatar: "DK",
    phone: "9871230020",
    email: "champion@acad.in",
    city: "Nagpur",
    state: "MH",
    interestedPlan: "Pro",
    stage: "New Lead",
    source: "Referral",
    referredBy: "Ravi Tiwari",
    assignedTo: "Ravi Tiwari",
    expectedMRR: 1000,
    expectedCloseDate: null,
    daysInCurrentStage: 1,
    totalDaysInPipeline: 1,
    priority: "Low",
    tags: [],
    notes: "Referral from existing customer",
    lastContactDate: null,
    nextFollowupDate: null,
    nextFollowupType: null,
    demoDate: null,
    demoTime: null,
    demoMode: null,
    proposalSentDate: null,
    convertedDate: null,
    lostDate: null,
    lostReason: null,
    estimatedStudents: 150,
    createdAt: "2026-04-11",
    updatedAt: "2026-04-11",
  },
];

export const followUps: FollowUp[] = [
  { id: "FU001", leadId: "LEAD001", leadName: "Star Coaching Centre", contactPerson: "Ramesh", phone: "9871230001", assignedTo: "Ravi", type: "Call", scheduledDate: "2026-04-11", scheduledTime: "10:00 AM", notes: "Negotiate pricing — they want 20% off Pro plan", status: "Pending", priority: "High", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU002", leadId: "LEAD007", leadName: "Excel Coaching Hub", contactPerson: "Suresh", phone: "9871230007", assignedTo: "Ravi", type: "Call", scheduledDate: "2026-04-11", scheduledTime: "2:00 PM", notes: "Follow up on proposal sent 8 Apr", status: "Pending", priority: "High", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU003", leadId: "LEAD002", leadName: "Gurukripa Classes", contactPerson: "Sunita", phone: "9871230002", assignedTo: "Pooja", type: "WhatsApp", scheduledDate: "2026-04-11", scheduledTime: "4:00 PM", notes: "Check if they reviewed the demo recording", status: "Pending", priority: "High", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU004", leadId: "LEAD009", leadName: "Aspire Institute", contactPerson: "Rohit", phone: "9871230009", assignedTo: "Ravi", type: "Call", scheduledDate: "2026-04-12", scheduledTime: "11:00 AM", notes: "Post-demo follow up — confirm plan interest", status: "Pending", priority: "High", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU005", leadId: "LEAD011", leadName: "Spark Tutorials", contactPerson: "Vijay", phone: "9871230011", assignedTo: "Ravi", type: "Meeting", scheduledDate: "2026-04-12", scheduledTime: "3:00 PM", notes: "In-person meeting to close the deal", status: "Pending", priority: "High", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU006", leadId: "LEAD004", leadName: "Bright Minds Institute", contactPerson: "Kavita", phone: "9871230004", assignedTo: "Neha", type: "Email", scheduledDate: "2026-04-13", scheduledTime: null, notes: "Send product brochure + pricing PDF", status: "Pending", priority: "Medium", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU007", leadId: "LEAD008", leadName: "Knowledge Tree", contactPerson: "Meera", phone: "9871230008", assignedTo: "Neha", type: "Call", scheduledDate: "2026-04-13", scheduledTime: "10:00 AM", notes: "First follow up after initial contact", status: "Pending", priority: "Medium", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU008", leadId: "LEAD003", leadName: "NextStep Academy", contactPerson: "Anil", phone: "9871230003", assignedTo: "Ravi", type: "Demo", scheduledDate: "2026-04-14", scheduledTime: "11:00 AM", notes: "Online demo via Google Meet", status: "Pending", priority: "High", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU009", leadId: "LEAD016", leadName: "Dream Academy", contactPerson: "Pooja", phone: "9871230016", assignedTo: "Ravi", type: "Demo", scheduledDate: "2026-04-15", scheduledTime: "3:00 PM", notes: "Online demo — Google Meet link shared", status: "Pending", priority: "Medium", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU010", leadId: "LEAD019", leadName: "Focus Point Classes", contactPerson: "Ravi S", phone: "9871230019", assignedTo: "Neha", type: "WhatsApp", scheduledDate: "2026-04-14", scheduledTime: null, notes: "Send WhatsApp message with trial offer", status: "Pending", priority: "Medium", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU011", leadId: "LEAD006", leadName: "Prime Study Circle", contactPerson: "Priya", phone: "9871230006", assignedTo: "Pooja", type: "Call", scheduledDate: "2026-04-10", scheduledTime: "11:00 AM", notes: "Cold outreach call — no response yet", status: "Overdue", priority: "Low", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU012", leadId: "LEAD010", leadName: "Zenith Classes", contactPerson: "Anita", phone: "9871230010", assignedTo: "Pooja", type: "Email", scheduledDate: "2026-04-09", scheduledTime: null, notes: "Initial outreach email — no reply", status: "Overdue", priority: "Low", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU013", leadId: "LEAD017", leadName: "Victory Classes", contactPerson: "Sunil", phone: "9871230017", assignedTo: "Neha", type: "WhatsApp", scheduledDate: "2026-04-08", scheduledTime: "2:00 PM", notes: "Sent intro message — no response", status: "Overdue", priority: "Medium", outcome: null, completedAt: null, snoozedUntil: null },
  { id: "FU014", leadId: "LEAD001", leadName: "Star Coaching Centre", contactPerson: "Ramesh", phone: "9871230001", assignedTo: "Ravi", type: "Call", scheduledDate: "2026-04-05", scheduledTime: "11:00 AM", notes: "Called re pricing — positive response", status: "Done", priority: "High", outcome: "Positive", completedAt: "2026-04-05T11:15:00Z", snoozedUntil: null },
  { id: "FU015", leadId: "LEAD009", leadName: "Aspire Institute", contactPerson: "Rohit", phone: "9871230009", assignedTo: "Ravi", type: "Demo", scheduledDate: "2026-04-09", scheduledTime: "2:00 PM", notes: "Demo done — very interested in Pro plan", status: "Done", priority: "High", outcome: "Positive", completedAt: "2026-04-09T15:05:00Z", snoozedUntil: null },
];

export const demos: Demo[] = [
  { id: "DEMO001", leadId: "LEAD003", leadName: "NextStep Academy", contactPerson: "Anil Mehta", phone: "9871230003", email: "nextstep@acad.in", assignedTo: "Ravi T", scheduledDate: "2026-04-14", scheduledTime: "11:00 AM", duration: 60, mode: "Online", meetLink: "meet.google.com/abc-defg-hij", location: null, status: "Scheduled", outcome: null, notes: "Focus on AI timetable", recordingLink: null, followUpScheduled: false },
  { id: "DEMO002", leadId: "LEAD016", leadName: "Dream Academy", contactPerson: "Pooja Mehta", phone: "9871230016", email: "dream@acad.in", assignedTo: "Ravi T", scheduledDate: "2026-04-15", scheduledTime: "3:00 PM", duration: 60, mode: "Online", meetLink: "meet.google.com/klm-nopq-rst", location: null, status: "Scheduled", outcome: null, notes: "Needs help with student data migration", recordingLink: null, followUpScheduled: false },
  { id: "DEMO003", leadId: "LEAD009", leadName: "Aspire Institute", contactPerson: "Rohit Gupta", phone: "9871230009", email: "aspire@inst.in", assignedTo: "Ravi T", scheduledDate: "2026-04-09", scheduledTime: "2:00 PM", duration: 75, mode: "Online", meetLink: "meet.google.com/uvw-xyz1-abc", location: null, status: "Completed", outcome: "Very Interested", notes: "V. impressed with AI Timetable and mobile app", recordingLink: "storage.techfly.com/demos/LEAD009.mp4", followUpScheduled: true },
  { id: "DEMO004", leadId: "LEAD002", leadName: "Gurukripa Classes", contactPerson: "Sunita Jain", phone: "9871230002", email: "guru@kripa.in", assignedTo: "Pooja M", scheduledDate: "2026-04-07", scheduledTime: "11:00 AM", duration: 90, mode: "In-Person", meetLink: null, location: "Nagpur Office", status: "Completed", outcome: "Interested", notes: "Needs more features in Fees module", recordingLink: null, followUpScheduled: true },
  { id: "DEMO005", leadId: "LEAD001", leadName: "Star Coaching Centre", contactPerson: "Ramesh Patil", phone: "9871230001", email: "star@coaching.in", assignedTo: "Ravi T", scheduledDate: "2026-04-05", scheduledTime: "3:00 PM", duration: 60, mode: "Online", meetLink: "meet.google.com/qwe-rtyu-iop", location: null, status: "Completed", outcome: "Very Interested", notes: "Price negotiation started", recordingLink: "storage.techfly.com/demos/LEAD001.mp4", followUpScheduled: true },
  { id: "DEMO006", leadId: "LEAD010", leadName: "Zenith Classes", contactPerson: "Anita Kapoor", phone: "9871230010", email: "zenith@classes.in", assignedTo: "Pooja M", scheduledDate: "2026-04-01", scheduledTime: "11:00 AM", duration: 45, mode: "Online", meetLink: "meet.google.com/zxc-vbnm-asd", location: null, status: "No Show", outcome: null, notes: "No response on meet link", recordingLink: null, followUpScheduled: false },
];

export const activities: LeadActivity[] = [
  { id: "ACT001", leadId: "LEAD001", type: "call", title: "Negotiating pricing", description: "Ramesh wants 20% discount on Pro plan. Next action: Get approval from Vikram before call tomorrow.", outcome: "Positive", performedBy: "Ravi Tiwari", scheduledAt: null, completedAt: "2026-04-10T11:30:00Z", duration: 22, nextAction: "Get approval from Vikram", nextActionDate: "2026-04-11" },
  { id: "ACT002", leadId: "LEAD001", type: "demo", title: "Demo Done", description: "Full product demo conducted. Very impressed with AI timetable.", outcome: "Positive", performedBy: "Ravi Tiwari", scheduledAt: "2026-04-05T15:00:00Z", completedAt: "2026-04-05T16:05:00Z", duration: 65, nextAction: null, nextActionDate: null },
  { id: "ACT003", leadId: "LEAD001", type: "follow_up", title: "Demo Scheduled", description: "Google Meet demo scheduled for 5 Apr 3:00 PM.", outcome: null, performedBy: "Ravi Tiwari", scheduledAt: "2026-04-04T10:00:00Z", completedAt: null, duration: null, nextAction: null, nextActionDate: null },
  { id: "ACT004", leadId: "LEAD001", type: "email", title: "Email Sent", description: "Sent intro email with brochure and pricing.", outcome: null, performedBy: "Ravi Tiwari", scheduledAt: null, completedAt: "2026-04-02T14:20:00Z", duration: null, nextAction: null, nextActionDate: null },
  { id: "ACT005", leadId: "LEAD001", type: "stage_change", title: "Lead Created", description: "Lead added via Social Media.", outcome: null, performedBy: "System", scheduledAt: null, completedAt: "2026-04-01T09:00:00Z", duration: null, nextAction: null, nextActionDate: null },
];
